spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=atmdb;encrypt=false
    username: sa
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080
